# Exported from Render on 2024-07-11T14:48:52Z
services:
- type: web
  name: spot-bot
  runtime: python
  repo: https://github.com/AccioMo/spot-bot
  plan: free
  envVars:
  - key: USRID
    sync: false
  - key: TELEGRAM_TOKEN
    sync: false
  - key: CLIENT_SECRET
    sync: false
  - key: CLIENT_ID
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 ws.py
version: "1"
